#include <stdint.h>

uint32_t inl(uint32_t port)
{
    uint32_t value;
    __asm__ __volatile__ ("inl %%dx, %%eax" : "=a" (value) : "d" (port));
    return value;
}

void outl(uint32_t port, uint32_t value)
{
    __asm__ __volatile__ ("outl %%eax, %%dx" : : "d" (port), "a" (value));
}

uint16_t pci_config_read_word(uint8_t bus, uint8_t slot, uint8_t func, uint8_t offset)
{
    uint32_t address;
    uint32_t lbus  = (uint32_t)bus;
    uint32_t lslot = (uint32_t)slot;
    uint32_t lfunc = (uint32_t)func;
    uint16_t tmp = 0;

    // Create configuration address as per Figure 1
    address = (uint32_t)((lbus << 16) | (lslot << 11) |
              (lfunc << 8) | (offset & 0xFC) | ((uint32_t)0x80000000));

    // Write out the address
    outl(0xCF8, address);
    // Read in the data
    // (offset & 2) * 8) = 0 will choose the first word of the 32-bit register
    tmp = (uint16_t)((inl(0xCFC) >> ((offset & 2) * 8)) & 0xFFFF);
    return tmp;
}

uint16_t pci_get_vendor_id(uint8_t bus, uint8_t slot)
{
    return pci_config_read_word(bus, slot, 0, 0);
}

const char *pci_get_vendor_name(uint16_t vendor_id)
{
    if (vendor_id == 0x1E4A) return "2CRSI SA";
    if (vendor_id == 0x1DA0) return "3M Company";
    if (vendor_id == 0x1F84) return "45Drives Ltd.";
    if (vendor_id == 0x1872) return "A & D Company, Ltd.";
    if (vendor_id == 0x160D) return "AAEON Electronics, Inc.";
    if (vendor_id == 0x1D28) return "Aava Mobile Oy";
    if (vendor_id == 0x1D92) return "Abaco Systems Inc.";
    if (vendor_id == 0x1C85) return "ABLIC Inc.";
    if (vendor_id == 0x1F60) return "ACCELECOM LTD.";
    if (vendor_id == 0x1F0E) return "Accipiter Systems, Inc.";
    if (vendor_id == 0x1113) return "Accton Technology Corporation";
    if (vendor_id == 0x14D6) return "Accusys Storage LTD.";
    if (vendor_id == 0x18E4) return "Acer Inc.";
    if (vendor_id == 0x1C94) return "Aces Electronics Co., Ltd.";
    if (vendor_id == 0x1B59) return "Achronix Semiconductor";
    if (vendor_id == 0x1DE8) return "Acqiris SA";
    if (vendor_id == 0x1C2A) return "Acromag, Inc";
    if (vendor_id == 0x1DE2) return "Action Star Technology Co., Ltd.";
    if (vendor_id == 0x4153) return "Active Silicon, Ltd.";
    if (vendor_id == 0x1CC1) return "ADATA Technology Co., Ltd.";
    if (vendor_id == 0x15B8) return "ADDI-DATA Gmbh";
    if (vendor_id == 0x144A) return "ADLINK Technology";
    if (vendor_id == 0x1E9C) return "Adnacom Inc.";
    if (vendor_id == 0x1CDA) return "ADTEC Corporation";
    if (vendor_id == 0xAD5A) return "ADVA Optical Networking SE";
    if (vendor_id == 0x1022) return "Advanced Micro Devices, Inc.";
    if (vendor_id == 0x130F) return "Advanet, Inc.";
    if (vendor_id == 0x13FE) return "Advantech Co., Ltd.";
    if (vendor_id == 0x1850) return "Advantest Corporation";
    if (vendor_id == 0x1D7C) return "Aerotech Inc";
    if (vendor_id == 0x1CF6) return "Aetina Corporation";
    if (vendor_id == 0x1B76) return "AIC Inc.";
    if (vendor_id == 0x1447) return "AIM GmbH";
    if (vendor_id == 0x4149) return "AIMOTIVE Kft.";
    if (vendor_id == 0x1F41) return "AIO Core Co., Ltd.";
    if (vendor_id == 0x1D36) return "Airbus Defence and Space GmbH";
    if (vendor_id == 0x1ACD) return "Airbus DS Electronics and Border Security GmbH";
    if (vendor_id == 0xF1D0) return "AJA Video";
    if (vendor_id == 0x1F98) return "Akeana, Inc.";
    if (vendor_id == 0x1F08) return "Akrostar Technology Co., Ltd.";
    if (vendor_id == 0x1096) return "Alacron";
    if (vendor_id == 0x1C0B) return "Alazar Technologies, Inc.";
    if (vendor_id == 0x1DC2) return "Alco Digital Devices Limited";
    if (vendor_id == 0x1DED) return "Alibaba (China) Co., Ltd.";
    if (vendor_id == 0x1B49) return "ALLDIS Computersystem GmbH";
    if (vendor_id == 0x1259) return "Allied Telesis Inc.";
    if (vendor_id == 0x194F) return "Allion Labs, Inc.";
    if (vendor_id == 0x1D67) return "Alltop Technology Co., Ltd";
    if (vendor_id == 0x1F6D) return "Allwinner Technology Co., Ltd.";
    if (vendor_id == 0x4144) return "Alpha Data Parallel Systems Ltd.";
    if (vendor_id == 0x1E5C) return "Alphawave IP";
    if (vendor_id == 0xAD00) return "Alta Data Technologies";
    if (vendor_id == 0x1D0F) return "Amazon";
    if (vendor_id == 0x101E) return "American Megatrends Incorporated";
    if (vendor_id == 0x101E) return "AMI US Holdings, Inc.";
    if (vendor_id == 0x1F35) return "Amlogic (CA) Co., Inc.";
    if (vendor_id == 0x1DEF) return "Ampere Computing, LLC";
    if (vendor_id == 0x18F8) return "Amphenol Corp.";
    if (vendor_id == 0x1A4C) return "Amulet Hotkey Ltd.";
    if (vendor_id == 0x1BFB) return "Analog Bits";
    if (vendor_id == 0x11D4) return "Analog Devices International";
    if (vendor_id == 0x12D6) return "Analogic Corporation";
    if (vendor_id == 0x1B12) return "Analogix Semiconductor";
    if (vendor_id == 0x27D1) return "Angelbird Technologies GmbH";
    if (vendor_id == 0x12DB) return "Annapolis Micro Systems, Inc.";
    if (vendor_id == 0x1852) return "Anritsu Corporation";
    if (vendor_id == 0x19EC) return "ANSYS, Inc.";
    if (vendor_id == 0x1BCD) return "Apacer Technology Inc.";
    if (vendor_id == 0x106B) return "Apple Computer";
    if (vendor_id == 0x5554) return "Applied Research Laboratories, The University of Texas at Austin";
    if (vendor_id == 0x1EF8) return "APTIV";
    if (vendor_id == 0x17ED) return "ARBOR Technology Corp";
    if (vendor_id == 0x17D3) return "Areca Technology Corporation";
    if (vendor_id == 0x13E6) return "ARGOSY RESEARCH INC.";
    if (vendor_id == 0x3475) return "Arista Networks, Inc.";
    if (vendor_id == 0x1AA1) return "Aristocrat Technologies Australia Pty Ltd.";
    if (vendor_id == 0x1A83) return "ARKUS Inc.";
    if (vendor_id == 0x13B5) return "ARM Ltd.";
    if (vendor_id == 0x1E17) return "Arnold & Richter Cine Technik GmbH & Co. Betriebs KG";
    if (vendor_id == 0x1E42) return "ART Beijing Science and Technology Development Co., Ltd.";
    if (vendor_id == 0x1DB4) return "Arteris Inc.";
    if (vendor_id == 0x1792) return "Artiza Networks, Inc.";
    if (vendor_id == 0x125B) return "ASIX Electronics Corp.";
    if (vendor_id == 0x1A03) return "ASPEED Technology Inc.";
    if (vendor_id == 0x1E5D) return "ASR Microelectronics Co., Ltd.";
    if (vendor_id == 0x1C18) return "ASSET InterTech, Inc.";
    if (vendor_id == 0x19D7) return "Astek Corporation";
    if (vendor_id == 0x1DFA) return "Astera Labs, Inc.";
    if (vendor_id == 0x11BF) return "Astrodesign, Inc.";
    if (vendor_id == 0x1A61) return "Astron Technology Corp.";
    if (vendor_id == 0x1BD0) return "Astronics Corporation";
    if (vendor_id == 0x1043) return "Asustek Computer Inc.";
    if (vendor_id == 0x1D58) return "Atech Flash Technology, Inc";
    if (vendor_id == 0x1DB2) return "ATP Electronics, Inc.";
    if (vendor_id == 0x1BDD) return "Atrust Computer Corp.";
    if (vendor_id == 0x175C) return "AudioScience, Inc.";
    if (vendor_id == 0x0A7C) return "Aurora Innovation Opco, Inc.";
    if (vendor_id == 0x1D50) return "Aurotek Corporation";
    if (vendor_id == 0x1A1F) return "Avago Technologies";
    if (vendor_id == 0x1DD7) return "AVAL DATA Corporation";
    if (vendor_id == 0x1AC2) return "Avalue Technology Inc.";
    if (vendor_id == 0x1F3C) return "Avant Technology";
    if (vendor_id == 0x1461) return "AVerMedia Technologies, Inc.";
    if (vendor_id == 0x18EF) return "Avery Design systems, Inc.";
    if (vendor_id == 0x1F34) return "Aviva Links";
    if (vendor_id == 0x1244) return "AVM Audiovisuelles Marketing und Computersysteme GmbH";
    if (vendor_id == 0x1A15) return "Axell Corporation";
    if (vendor_id == 0x1F4B) return "Axera Semiconductor (Shanghai) Co., Ltd";
    if (vendor_id == 0x1E6B) return "Axiado Corporation";
    if (vendor_id == 0x1E0C) return "Axiomtek Co., Ltd.";
    if (vendor_id == 0x1EF0) return "Ayar Labs";
    if (vendor_id == 0x1A3B) return "AzureWave Technologies, Inc.";
    if (vendor_id == 0x1D84) return "b-plus technologies GmbH";
    if (vendor_id == 0x119D) return "B.U.G. MORI SEIKI CO., LTD.";
    if (vendor_id == 0xB4C0) return "B4Com Technologies LLC";
    if (vendor_id == 0x0BAE) return "Bachmann electronic GmbH";
    if (vendor_id == 0x1B9F) return "BAE Systems";
    //if (vendor_id == 0x1D39) return "Baikal Electronics, JSC (*Suspended)";
    if (vendor_id == 0x13CC) return "Barco, Inc.";
    if (vendor_id == 0x1AE8) return "Basler AG";
    if (vendor_id == 0x1217) return "BayHub Technology Inc";
    if (vendor_id == 0x17CE) return "BCM Advanced Research";
    if (vendor_id == 0x1C78) return "Bechtel Marine Propulsion Corporation";
    if (vendor_id == 0x1C2F) return "Beckhoff Automation GmbH & Co. KG";
    if (vendor_id == 0x1024) return "Beijing Dajia Internet Information Technology Co., Ltd.";
    if (vendor_id == 0x1F02) return "Beijing Dayu Technology Co.,Ltd";
    if (vendor_id == 0x1E18) return "Beijing GuangRunTong Technology Development Co.,Ltd";
    if (vendor_id == 0x1C5F) return "Beijing Memblaze Technology Co. Ltd.";
    //if (vendor_id == 0x1E78) return "Beijing SenseTime Technology Development Co.,Ltd (*Suspended)";
    if (vendor_id == 0x1DCF) return "Beijing Sinead Technology Co., Ltd.";
    if (vendor_id == 0x9D32) return "Beijing Starblaze Technology Co., LTD";
    if (vendor_id == 0x8088) return "Beijing Wangxun Technology Co., Ltd.";
    if (vendor_id == 0x1C75) return "Bellwether Electronic Corp.";
    if (vendor_id == 0x1B05) return "Benchmark Electronics, Inc.";
    if (vendor_id == 0x3442) return "Bihl + Wiedemann GmbH";
    if (vendor_id == 0x1C6F) return "Bios Corporation";
    if (vendor_id == 0x1A11) return "BitifEye Digital Test Solutions GmbH";
    if (vendor_id == 0x1DEE) return "Biwin Storage Technology Co., Ltd.";
    if (vendor_id == 0x7248) return "BizLink Technology, Inc.";
    if (vendor_id == 0x1EF1) return "Black Sesame Technologies Co., Ltd.";
    if (vendor_id == 0x1C05) return "Blackberry QNX";
    if (vendor_id == 0xBDBD) return "Blackmagic Design Pty Ltd";
    if (vendor_id == 0x1E38) return "Blaize";
    if (vendor_id == 0x00BB) return "Bloombase";
    if (vendor_id == 0x15E0) return "Blue Coat Systems";
    if (vendor_id == 0x00B0) return "Blue Origin, LLC";
    if (vendor_id == 0x16F2) return "Bosch Rexroth AG";
    if (vendor_id == 0x1E16) return "BOXX Technologies, LLC";
    if (vendor_id == 0x1E7C) return "Brainchip, Inc.";
    if (vendor_id == 0x9D68) return "Brite Semiconductor (Shanghai) Corporation, Ltd.";
    if (vendor_id == 0x14E4) return "Broadcom Limited";
    if (vendor_id == 0x1C4F) return "Bruker Corporation";
    if (vendor_id == 0x1154) return "Buffalo Inc.";
    if (vendor_id == 0x119F) return "BULL SAS";
    if (vendor_id == 0x1E3D) return "Burlywood, Inc";
    if (vendor_id == 0x9000) return "C-Core Technology Co., Ltd.";
    if (vendor_id == 0x1F18) return "C-Payne PCB Design";
    if (vendor_id == 0x1E3A) return "Cactus Technologies, Limited";
    if (vendor_id == 0x17CD) return "Cadence Design Systems";
    if (vendor_id == 0xCABC) return "Cambricon Technologies Corporation Limited";
    if (vendor_id == 0x11AC) return "Canon, Inc.";
    if (vendor_id == 0x197D) return "Cap Co., Ltd.";
    if (vendor_id == 0x1F1E) return "CARIAD SE";
    if (vendor_id == 0x1C96) return "Carina System Co., Ltd.";
    if (vendor_id == 0x1F8B) return "Carl Zeiss Meditec AG";
    if (vendor_id == 0x1DDC) return "Carlisle Interconnect Technologies";
    if (vendor_id == 0x1ACD) return "Cassidian";
    if (vendor_id == 0x1E97) return "Caswell Inc.";
    if (vendor_id == 0x1DFD) return "CDSG";
    if (vendor_id == 0x1F7B) return "CELESTIAL AI INC";
    if (vendor_id == 0x18D4) return "Celestica";
    if (vendor_id == 0x1169) return "Centre for Development of Advanced Computing";
    if (vendor_id == 0x123C) return "CENTURY SYSTEMS Co.,Ltd.";
    if (vendor_id == 0x1B42) return "Ceremorphic, Inc";
    if (vendor_id == 0x10DC) return "CERN";
    //if (vendor_id == 0x0731) return "Changsha Jingjia Microelectronics Co., Ltd. (*Suspended)";
    if (vendor_id == 0x1F20) return "Channel Well Technology Co., Ltd.";
    if (vendor_id == 0x1CEE) return "Chant Sincere Co., Ltd.";
    if (vendor_id == 0x1425) return "Chelsio Communications";
    if (vendor_id == 0xD20C) return "Chengdu BeiZhongWangXin Technology Co.Ltd";
    if (vendor_id == 0x1D94) return "Chengdu Higon Integrated Circuit Design Co., Ltd.";
    if (vendor_id == 0x1EA5) return "Chief Land Electronic Co., Ltd.";
    if (vendor_id == 0x1EF4) return "CHINA AVIATION OPTICAL-ELECTRICAL PRECISION ELECTRONIC SHENZHEN CO.,LTD";
    if (vendor_id == 0x1F94) return "Chipsea Technologies (Shenzhen) Corp.";
    if (vendor_id == 0x17E8) return "Chrontel, Inc.";
    if (vendor_id == 0x1A43) return "Chuo Electronics Co., Ltd.";
    if (vendor_id == 0x1D47) return "Ciena Corporation";
    if (vendor_id == 0x1013) return "Cirrus Logic, Inc.";
    if (vendor_id == 0x1137) return "Cisco Systems, Inc.";
    if (vendor_id == 0xC5EC) return "Citadel Securities LLC";
    if (vendor_id == 0x5853) return "Citrix Systems UK Ltd";
    if (vendor_id == 0x1F6C) return "CIX Technology (Shanghai) Co., Ltd";
    if (vendor_id == 0x04DB) return "CLEVER INFORMATION INC.";
    if (vendor_id == 0x1558) return "Clevo Co.";
    if (vendor_id == 0x1EE6) return "Clientron Corp.";
    if (vendor_id == 0x1F51) return "CloudNine Information Technologies Co. Ltd";
    if (vendor_id == 0x1D1D) return "CNEX LABS Inc.";
    if (vendor_id == 0xCCDE) return "Code Construct Pty Ltd";
    if (vendor_id == 0x12B7) return "Cognex Corporation";
    if (vendor_id == 0x1830) return "Cohu, Inc.";
    if (vendor_id == 0x15D7) return "Collins Aerospace";
    if (vendor_id == 0x1D38) return "Colorado Engineering Inc.";
    if (vendor_id == 0x1DE6) return "Communication Automation Corporation";
    if (vendor_id == 0x14C0) return "Compal Electronics, Inc.";
    if (vendor_id == 0x1C69) return "Comtel Electronics GmbH";
    if (vendor_id == 0x125F) return "Concurrent Technologies";
    if (vendor_id == 0x1A2F) return "congatec GmbH";
    if (vendor_id == 0x12C4) return "Connect Tech Inc.";
    if (vendor_id == 0x1F81) return "CONNPRO ind.";
    if (vendor_id == 0x1221) return "Contec Co., Ltd.";
    if (vendor_id == 0x1DA8) return "Corigine Inc.";
    if (vendor_id == 0x434E) return "Cornelis Networks, Inc.";
    if (vendor_id == 0x1CFA) return "Corsair Memory, Inc";
    if (vendor_id == 0x1C46) return "Cosmotechs Co., Ltd.";
    if (vendor_id == 0x136C) return "CPI Technologies, Inc.";
    if (vendor_id == 0x1102) return "Creative Technology Ltd";
    if (vendor_id == 0x1E23) return "Credo Semiconductor, Inc.";
    if (vendor_id == 0xCCEC) return "Curtiss-Wright Controls Embedded Computing";
    if (vendor_id == 0x1EA2) return "Cyber Cogs";
    if (vendor_id == 0x1F82) return "d-Matrix Corporation";
    if (vendor_id == 0x18F2) return "Dai-Ichi Seiko Co., Ltd(I-PEX)";
    if (vendor_id == 0x1E7D) return "Daichu Technologies Co.,Ltd.";
    if (vendor_id == 0x19EB) return "DAIHEN Corporation";
    if (vendor_id == 0x1BFA) return "Daiichi Jitsugyo Viswill Co., Ltd";
    if (vendor_id == 0x1C33) return "Daktronics";
    if (vendor_id == 0x1C33) return "Daktronics, Inc.";
    if (vendor_id == 0x194A) return "Dap Holding B.V.";
    if (vendor_id == 0x1E3B) return "DapuStor Corporation";
    if (vendor_id == 0x0303) return "DAQ System";
    if (vendor_id == 0x1E1A) return "DataDirect Networks, Inc.";
    if (vendor_id == 0x1D4C) return "Datawise Systems, Inc.";
    //if (vendor_id == 0x1CB8) return "Dawning Information Industry Co., Ltd. (*Suspended)";
    if (vendor_id == 0x1F0D) return "DeGirum Corporation";
    if (vendor_id == 0x1A0E) return "DekTec Digital Video B.V.";
    if (vendor_id == 0x1E33) return "Delkin Devices";
    if (vendor_id == 0x1028) return "Dell Computer Corporation";
    if (vendor_id == 0x1A05) return "Delta Electronics, Inc.";
    if (vendor_id == 0x1B66) return "Deltatec";
    if (vendor_id == 0x1F5F) return "DENKEI TRADING (SHANGHAI) CO.,LTD";
    if (vendor_id == 0x1192) return "Densan Co., Ltd.";
    if (vendor_id == 0x1D78) return "Dera co., Ltd.";
    if (vendor_id == 0x1C04) return "Dexon Systems Ltd";
    if (vendor_id == 0x15BD) return "DFI Inc.";
    if (vendor_id == 0x1D4C) return "Diamanti, Inc.";
    if (vendor_id == 0x114F) return "Digi International Inc.";
    if (vendor_id == 0xDD01) return "Digital Devices";
    if (vendor_id == 0x18FD) return "Digital Media Professionals, Inc.";
    if (vendor_id == 0x1ED8) return "Digiteq Automotive s.r.o.";
    if (vendor_id == 0x12D8) return "Diodes Incorporated";
    if (vendor_id == 0x119D) return "DMG MORI Digital Co., LTD.";
    if (vendor_id == 0x11C8) return "Dolphin Interconnect Solutions AS";
    if (vendor_id == 0x1E82) return "Dongguan Yizhao Electronic Co.,Ltd.";
    if (vendor_id == 0x1E93) return "Douyin Vision Co., Ltd.";
    if (vendor_id == 0x1EDE) return "DreamBig Semiconductor Inc";
    if (vendor_id == 0x1E96) return "Drut Technologies Inc.";
    if (vendor_id == 0x4453) return "dSPACE GmbH";
    if (vendor_id == 0x1BFC) return "duagon AG";
    if (vendor_id == 0x3100) return "Dynabook Inc.";
    if (vendor_id == 0x1B98) return "E.E.P.D. GmbH";
    if (vendor_id == 0x1974) return "Eberspächer Electronics GmbH & Co. KG";
    if (vendor_id == 0x177C) return "EBRAINS, INC.";
    if (vendor_id == 0x1DD6) return "ECRIN SYSTEMS";
    if (vendor_id == 0x1428) return "EDEC Linsey System Co., Ltd.";
    if (vendor_id == 0x1F30) return "Edelweiss, LLC";
    if (vendor_id == 0x1ECE) return "EdgeQ, Inc.";
    if (vendor_id == 0x1F7A) return "Efinix, Inc.";
    if (vendor_id == 0x1F42) return "EGK ELECTRONICS TECHNOLOGY LIMITED";
    if (vendor_id == 0x1DE5) return "Eietic Communications Inc";
    if (vendor_id == 0x181D) return "eInfochips, Inc.";
    if (vendor_id == 0x1227) return "EIZO Rugged Solutions";
    if (vendor_id == 0xE4BF) return "EKF Elektronik GmbH";
    if (vendor_id == 0x1F2D) return "Elastics.cloud";
    if (vendor_id == 0x13B9) return "ELECOM CO LTD";
    if (vendor_id == 0x1C7F) return "Elektrobit Austria GmbH";
    if (vendor_id == 0x1D4B) return "Elektrosfera LTD.";
    if (vendor_id == 0x1019) return "Elitegroup Computer Systems Inc.";
    if (vendor_id == 0x1F8E) return "Eliyan Corp";
    if (vendor_id == 0x1C24) return "Elma Electronic Inc";
    if (vendor_id == 0x1433) return "Eltec Elektronik AG";
    if (vendor_id == 0x2782) return "Emdoor Digital Technology Co., Ltd";
    if (vendor_id == 0x1E5E) return "Emergent Vision Technologies Inc";
    if (vendor_id == 0x1EBD) return "EMERGETECH Company Ltd.";
    if (vendor_id == 0xEA50) return "Emerson Automation Solutions";
    if (vendor_id == 0xEACE) return "Endace Technology Ltd.";
    if (vendor_id == 0x1F00) return "Enercon Technologies";
    if (vendor_id == 0xEFAB) return "Enfabrica Corporation";
    if (vendor_id == 0x123D) return "Engineering Design Team, Inc.";
    if (vendor_id == 0x1D8F) return "ENYX";
    // EPIX, INC.,
    if (vendor_id == 0x1A25) return "Ericsson AS";
    if (vendor_id == 0x12FE) return "esd electronics gmbh";
    if (vendor_id == 0x1E10) return "eSOL Co.,Ltd.";
    if (vendor_id == 0x1E0A) return "Esperanto Technologies, Inc";
    if (vendor_id == 0x1E45) return "ESSENCORE Limited";
    if (vendor_id == 0x1DF3) return "Ethernity Networks Ltd";
    if (vendor_id == 0x1F43) return "Ethernovia Inc.";
    if (vendor_id == 0x1977) return "Etion Create (Pty) Ltd.";
    if (vendor_id == 0x1EC2) return "eTopus Technology Inc.";
    if (vendor_id == 0x1B6F) return "Etron Technology, Inc.";
    if (vendor_id == 0x1805) return "Euresys s.a.";
    if (vendor_id == 0x1D86) return "Evertz Microsystems Ltd.";
    if (vendor_id == 0x3842) return "EVGA Corporation";
    if (vendor_id == 0x4556) return "Evident Corporation";
    if (vendor_id == 0x1F8C) return "Exascend, Inc.";
    if (vendor_id == 0x1BC1) return "EXFO Inc.";
    if (vendor_id == 0x1EA3) return "Expedera, Inc";
    if (vendor_id == 0x1CAD) return "EXTOLL GmbH";
    if (vendor_id == 0x5845) return "Extreme Engineering Solutions";
    if (vendor_id == 0xF5F5) return "F5 Networks, Inc.";
    if (vendor_id == 0x1D9B) return "Facebook";
    if (vendor_id == 0x1DC5) return "FADU Inc.";
    if (vendor_id == 0x188B) return "Faraday Technology Corporation";
    if (vendor_id == 0x1463) return "Fast Corporation";
    if (vendor_id == 0x1D8C) return "FASTWEL Group Co. Ltd";
    if (vendor_id == 0xFDEF) return "Fermionic Design Private Limited";
    //if (vendor_id == 0x1D8D) return "Fiberhome Telecommunication Technologies (*Suspended)";
    if (vendor_id == 0x190E) return "Fidus Systems Inc.";
    if (vendor_id == 0x1E1B) return "Firm INFORMTEST Ltd.";
    if (vendor_id == 0x1895) return "Flextronics International";
    if (vendor_id == 0x1EFB) return "Flexxon Pte Ltd";
    if (vendor_id == 0x1CB5) return "Focusrite Audio Engineering Ltd";
    if (vendor_id == 0x1778) return "For-A Company Limited";
    if (vendor_id == 0x1F6A) return "Ford Motor Company";
    if (vendor_id == 0x1165) return "Foresight Imaging LLC";
    if (vendor_id == 0x1796) return "Forschungszentrum Jülich GmbH";
    if (vendor_id == 0x1A29) return "Fortinet, Inc.";
    // Forum Test Company,
    if (vendor_id == 0x1DC6) return "Fox Crypto B.V.";
    if (vendor_id == 0x105B) return "Foxconn (Hon Hai)";
    if (vendor_id == 0xF111) return "Framework Computer Inc.";
    if (vendor_id == 0x1F79) return "Fraunhofer Institute for Industrial Mathematics (ITWM)";
    if (vendor_id == 0x16EA) return "Fuji Electric Co., Ltd.";
    if (vendor_id == 0x1135) return "FUJIFILM Business Innovation Corp.";
    if (vendor_id == 0x10CF) return "Fujitsu Limited";
    if (vendor_id == 0x1ED2) return "FuriosaAI, Inc.";
    if (vendor_id == 0x10B0) return "Gainward Technology Int'l Limited";
    if (vendor_id == 0x1B4C) return "Galaxy Microsystems Ltd.";
    if (vendor_id == 0x17F9) return "GemTek Technology Co., Ltd.";
    if (vendor_id == 0x0123) return "General Dynamics Mission Systems, Inc.";
    if (vendor_id == 0x1F9C) return "General Motors";
    if (vendor_id == 0x1D32) return "Genesis Co.,Ltd";
    if (vendor_id == 0x17A0) return "Genesys Logic, Inc.";
    if (vendor_id == 0x15E7) return "GET Engineering Corporation";
    if (vendor_id == 0x165C) return "Gidel Ltd.";
    if (vendor_id == 0x1458) return "Giga-Byte Technology Co., Ltd.";
    if (vendor_id == 0x1F88) return "GL Communications Inc.";
    if (vendor_id == 0x6766) return "Glenfly Tech Co., Ltd.";
    if (vendor_id == 0x1AC1) return "Global Unichip Corp.";
    if (vendor_id == 0xECAB) return "GM Cruise LLC";
    if (vendor_id == 0x140E) return "GOEPEL electronic GmbH";
    if (vendor_id == 0x1D2D) return "Good Way Technology Co., Ltd.";
    if (vendor_id == 0x1AE0) return "Google, Inc.";
    if (vendor_id == 0x1A83) return "Gopher Inc.";
    if (vendor_id == 0x1C5E) return "GopherTec Inc.";
    if (vendor_id == 0x22C2) return "Gowin Semiconductor Corporation";
    if (vendor_id == 0x1EF6) return "GrAI Matter Labs";
    if (vendor_id == 0x1BD7) return "Granite River Labs Inc.";
    if (vendor_id == 0x1D95) return "Graphcore Ltd";
    if (vendor_id == 0x1F8D) return "Graviton LTD";
    if (vendor_id == 0x1B95) return "Green Hills Software";
    if (vendor_id == 0x1BF5) return "Greenliant";
    if (vendor_id == 0x1DE0) return "Groq, Inc.";
    if (vendor_id == 0x1E4C) return "GSI Technology";
    if (vendor_id == 0x6688) return "GUANGZHOU MAXSUN INFORMATION TECHNOLOGY CO., LTD.";
    if (vendor_id == 0x6D5E) return "Guntermann & Drunck GmbH";
    if (vendor_id == 0x1253) return "Guzik Technical Enterprises";
    if (vendor_id == 0x1D29) return "Hagiwara Solutions Co., Ltd.";
    if (vendor_id == 0x1E60) return "HAILO Technologies LTD.";
    if (vendor_id == 0x11A1) return "Hamamatsu Photonics K.K.";
    if (vendor_id == 0x1F96) return "Hana Electronics Indústria e Comércio LTDA";
    if (vendor_id == 0x1F83) return "Hangzhou Clounix Technology Limited";
    if (vendor_id == 0x0823) return "Hangzhou Hongjun Microelectronics Co., Ltd.";
    if (vendor_id == 0x19CB) return "Hartmann Electronic GmbH";
    if (vendor_id == 0x1C07) return "HCL Technologies Ltd";
    if (vendor_id == 0x19A6) return "HDL Design House";
    if (vendor_id == 0x1EAB) return "Hefei DATANG Storage Technology Co.,LTD.";
    if (vendor_id == 0x112B) return "Heidelberger Druckmaschinen AG";
    if (vendor_id == 0x1E85) return "Heitec AG";
    if (vendor_id == 0x1ACD) return "Hensoldt Sensors GmbH";
    if (vendor_id == 0x78C0) return "Herrick Technology Laboratories (HTL), Inc.";
    if (vendor_id == 0x103C) return "Hewlett Packard";
    if (vendor_id == 0x1590) return "Hewlett Packard Enterprise";
    if (vendor_id == 0x1FAA) return "Hexaflake (Shanghai) Information Technology Co., Ltd.";
    if (vendor_id == 0x1C55) return "Hexagon Metrology S.P.A.";
    if (vendor_id == 0x15CF) return "Hilscher Gesellschaft fuer Systemautomation mbH";
    if (vendor_id == 0x184C) return "Hirose Electric USA Inc.";
    if (vendor_id == 0x0800) return "Hirota Seisakusho Limited";
    if (vendor_id == 0x1F28) return "HisunTest Technologies (Beijing) Co., Ltd";
    if (vendor_id == 0x1FCD) return "Hitachi High-Tech Corporation";
    if (vendor_id == 0x1250) return "Hitachi Solutions Technology, Ltd.";
    if (vendor_id == 0x1367) return "Hitachi Zosen Corporation";
    if (vendor_id == 0x1054) return "Hitachi, Ltd.";
    if (vendor_id == 0x14A9) return "Hivertec, Inc.";
    if (vendor_id == 0x1BEE) return "HMS Technology Center Ravensburg GmbH";
    if (vendor_id == 0x10AC) return "Honeywell Inc.";
    if (vendor_id == 0x1F7C) return "Hong Kong Applied Science and Technology Research Institute (ASTRI)";
    if (vendor_id == 0x1F37) return "Hongkong Likfo (China) Business LTD";
    if (vendor_id == 0x1EE7) return "Honor Device Co., Ltd.";
    if (vendor_id == 0x1ED0) return "Hosin Global Electronics Co., LTD.";
    if (vendor_id == 0x103C) return "HP Inc.";
    if (vendor_id == 0x19E5) return "Huawei Technologies Co., Ltd.";
    if (vendor_id == 0x1F6F) return "Huaxia Smart Chip (Beijing) Technology Co., LTD";
    if (vendor_id == 0x1C82) return "HUBER+SUHNER Inc";
    //if (vendor_id == 0x21B4) return "Hunan Goke Microelectronics Co., Ltd. (*Suspended)";
    if (vendor_id == 0x10FC) return "I-O Data Device, Inc.";
    if (vendor_id == 0x18F2) return "I-PEX (Dai-ichi Seiko)";
    if (vendor_id == 0x1AAC) return "IBASE Technology Inc.";
    if (vendor_id == 0x11CA) return "IBEX Technology, Co. Ltd.";
    if (vendor_id == 0x1014) return "IBM";
    if (vendor_id == 0x1B53) return "iD corporation";
    if (vendor_id == 0x180C) return "IEI Integration Corp.";
    if (vendor_id == 0x1C9D) return "Illumina";
    if (vendor_id == 0x15D1) return "Infineon Technologies AG";
    if (vendor_id == 0x1EDA) return "infodas GmbH";
    if (vendor_id == 0x1F1D) return "Initio (HK) Corporation Limited";
    if (vendor_id == 0x1BC0) return "InnoDisk Corporation";
    if (vendor_id == 0x1DBE) return "INNOGRIT CORPORATION";
    if (vendor_id == 0x1EC8) return "Innosilicon Technology Ltd";
    if (vendor_id == 0x1CFB) return "Innotech Corporation";
    if (vendor_id == 0x1771) return "InnoVision Multimedia, Ltd.";
    if (vendor_id == 0x1BD4) return "Inspur Electronic Information Industry Co., Ltd.";
    if (vendor_id == 0x1D4D) return "Integrated Design Tools, Inc.";
    if (vendor_id == 0x1E99) return "INTEGRATED SERVICE TECHNOLOGY Inc.";
    if (vendor_id == 0x8086) return "Intel Corporation";
    if (vendor_id == 0x0909) return "Intelligence Draw Microelectronics(Nanjing) Co., Ltd.";
    if (vendor_id == 0x2021) return "Intelligent Memory Limited";
    if (vendor_id == 0x1EA7) return "IntelliProp Inc.";
    if (vendor_id == 0x1739) return "Interface Concept";
    if (vendor_id == 0x1147) return "Interface Corporation";
    if (vendor_id == 0x1A6E) return "International Game Technology";
    if (vendor_id == 0x1BDC) return "Intrado Inc.";
    if (vendor_id == 0x1E12) return "Introspect Technology";
    if (vendor_id == 0x7548) return "INUITIVE LTD.";
    if (vendor_id == 0x1B26) return "INVEA-TECH a.s.";
    if (vendor_id == 0x1170) return "Inventec Corporation";
    if (vendor_id == 0x5353) return "iodyne";
    if (vendor_id == 0x1546) return "IOI Technology Corporation";
    if (vendor_id == 0x1E50) return "IP3 Tech (HK) Limited";
    if (vendor_id == 0x1F04) return "iPasslabs Technology Co. Ltd.";
    if (vendor_id == 0x1E6A) return "IRISO Electronics Co., Ltd";
    if (vendor_id == 0x1283) return "ITE Tech. Inc.";
    if (vendor_id == 0x0B48) return "ITTIM Technology Limited";
    if (vendor_id == 0x1BEE) return "IXXAT Automation GmbH";
    if (vendor_id == 0x1F8A) return "J-Squared Technologies Inc.";
    if (vendor_id == 0x10D3) return "Jabil Circuit Inc.";
    if (vendor_id == 0x1817) return "JAE";
    if (vendor_id == 0x1F72) return "Jane Street Group, LLC";
    if (vendor_id == 0x1D12) return "JESS-LINK PRODUCTS CO., LTD.";
    if (vendor_id == 0x1E7F) return "Jiangsu Huacun Electronic Technology Co., Ltd.";
    if (vendor_id == 0x1EEC) return "Jiangsu Viscore Technologies Co.,Ltd";
    if (vendor_id == 0x1E68) return "Jiangsu Xinsheng Intelligent Technology Co., Ltd.";
    if (vendor_id == 0x5959) return "Jiangsu Yunyong Electronics and Technology Co., Ltd.";
    if (vendor_id == 0xD011) return "Jiedao (Shanghai) System Integration Co., Ltd.";
    if (vendor_id == 0x197B) return "JMicron Technology Corporation";
    if (vendor_id == 0x1C65) return "Jump Trading Group";
    if (vendor_id == 0x1304) return "Juniper Networks";
    if (vendor_id == 0x13D6) return "K.I. Technology Co., Ltd";
    if (vendor_id == 0x18B2) return "K.K. Rocky";
    if (vendor_id == 0x1EEB) return "Kaimai Tech Ltd.";
    if (vendor_id == 0x1D26) return "KALRAY";
    if (vendor_id == 0x1E6F) return "Kandou Bus S.A.";
    if (vendor_id == 0x13A1) return "Kawasaki Heavy Industries, Ltd.";
    if (vendor_id == 0x1D2A) return "KAYA Instruments Ltd";
    if (vendor_id == 0xCEBA) return "KEBA AG";
    if (vendor_id == 0x1A3F) return "KEL Corporation";
    if (vendor_id == 0x1ABB) return "Key ASIC Berhad";
    if (vendor_id == 0x1B2A) return "Keyence Corporation";
    if (vendor_id == 0x15BC) return "Keysight Technologies";
    if (vendor_id == 0x1E58) return "Kinara Inc.";
    if (vendor_id == 0x2646) return "Kingston Technology Company";
    if (vendor_id == 0x1E0F) return "Kioxia Corporation";
    if (vendor_id == 0x1BBA) return "KLA-Tencor";
    if (vendor_id == 0x1629) return "Kongsberg Defence & Aerospace AS - Spacetec";
    if (vendor_id == 0x16CB) return "Konica Minolta Holdings Inc.";
    if (vendor_id == 0x1059) return "Kontron";
    if (vendor_id == 0x1A07) return "Kvaser AB";
    if (vendor_id == 0x1893) return "Kyocera Corporation";
    if (vendor_id == 0x1738) return "L3Harris Technologies, Inc.";
    if (vendor_id == 0x1D71) return "Laird Connectivity, LLC";
    if (vendor_id == 0x1F9B) return "Lantronix, Inc.";
    if (vendor_id == 0x1204) return "Lattice Semiconductor Corporation";
    if (vendor_id == 0x1407) return "Lava Computer MFG. Inc.";
    if (vendor_id == 0x107D) return "Leadtek Research Inc.";
    if (vendor_id == 0x1F74) return "Leica Camera AG";
    if (vendor_id == 0x17AA) return "Lenovo";
    if (vendor_id == 0x1F50) return "LeRain Technology Co., Ltd";
    if (vendor_id == 0x1854) return "LG Electronics";
    if (vendor_id == 0x060E) return "Lightelligence, Inc.";
    if (vendor_id == 0x1ECA) return "Lightmatter";
    if (vendor_id == 0x1E3F) return "Linaro Limited";
    if (vendor_id == 0x1D14) return "Lintes Technology Co., Ltd.";
    if (vendor_id == 0x1DCD) return "Liqid Inc";
    if (vendor_id == 0x1F13) return "Listan GmbH";
    if (vendor_id == 0x14A4) return "Lite-On Technology Corporation";
    if (vendor_id == 0x1784) return "Lockheed Martin";
    if (vendor_id == 0x1DBD) return "Logic Fruit Technologies Pvt Ltd";
    if (vendor_id == 0x0014) return "Loongson Technology Corporation Limited";
    if (vendor_id == 0x1880) return "LOTES Co., Ltd";
    if (vendor_id == 0x1F59) return "Lucid Vision Labs, Inc.";
    if (vendor_id == 0x1BDF) return "LUXSHARE-ICT, Inc.";
    if (vendor_id == 0x1CAB) return "Lynx Software Technologies, Inc.";
    if (vendor_id == 0x1E9F) return "Lynxi Technologies Ltd., Co.";
    if (vendor_id == 0x1D27) return "M31 Technology Corporation";
    if (vendor_id == 0x1916) return "Macnica, Inc.";
    if (vendor_id == 0x1D8E) return "MACOM Technology Solutions Inc.";
    if (vendor_id == 0x2337) return "Macronix International Co., Ltd.";
    if (vendor_id == 0x1F52) return "MangoBoost Inc.";
    if (vendor_id == 0x137A) return "Mark of the Unicorn, Inc.";
    if (vendor_id == 0x1DCA) return "Marvell Semiconductor, Inc.";
    if (vendor_id == 0x16E2) return "Marvin Test Solutions, Inc.";
    if (vendor_id == 0x4D56) return "Matrix Vision GmbH";
    if (vendor_id == 0x102B) return "Matrox Graphics Inc.";
    if (vendor_id == 0x1E4B) return "Maxio Technology(Hangzhou)Co.,Ltd.";
    if (vendor_id == 0x1E43) return "MaxLinear Inc";
    if (vendor_id == 0x1DD0) return "McDowell Signal Processing, LLC";
    if (vendor_id == 0x1AA2) return "Media Links Co., LTD.";
    if (vendor_id == 0x14C3) return "MediaTek Incorporation";
    if (vendor_id == 0x1E39) return "MEDION AG";
    if (vendor_id == 0x1F93) return "Mega Electronics Co., Ltd.";
    if (vendor_id == 0x10A0) return "Meidensha Corporation";
    if (vendor_id == 0x1360) return "Meinberg Funkuhren GmbH & Co. KG";
    if (vendor_id == 0x152E) return "Melec Inc.";
    if (vendor_id == 0x1CA0) return "MEMORIGHT";
    if (vendor_id == 0x1E2E) return "Mercedes-Benz R&D North America, Inc.";
    if (vendor_id == 0x1134) return "Mercury Computer Systems, Inc.";
    if (vendor_id == 0x9999) return "MetaX Integrated Circuits (Shanghai) Co., Ltd.";
    if (vendor_id == 0x1462) return "Micro-Star International Co., Ltd.";
    if (vendor_id == 0x11F8) return "Microchip Technology";
    if (vendor_id == 0x1344) return "Micron Technology, Inc.";
    if (vendor_id == 0x1414) return "Microsoft";
    if (vendor_id == 0x4D54) return "Microtechnica Co., Ltd.";
    if (vendor_id == 0x1322) return "MIS Corporation";
    if (vendor_id == 0x22DB) return "Missing Link Electronics, Inc.";
    if (vendor_id == 0x1DAF) return "MIT Lincoln Laboratory";
    if (vendor_id == 0x1071) return "MiTAC International Corporation";
    if (vendor_id == 0x10BA) return "Mitsubishi Electric Corporation";
    if (vendor_id == 0x1F07) return "Mitsui Chemicals America, Inc.";
    if (vendor_id == 0x1547) return "Mitutoyo Corporation";
    if (vendor_id == 0x1C8C) return "Mobiveil, Inc.";
    if (vendor_id == 0x1F36) return "Moffett AI Technology Shenzhen Co., Ltd";
    if (vendor_id == 0x10D2) return "Molex LLC";
    if (vendor_id == 0x1B00) return "Montage Technology Co., Ltd.";
    if (vendor_id == 0x1ED5) return "Moore Threads Technology Co.,Ltd";
    if (vendor_id == 0x1F0A) return "Motorcomm Electronic Technology Co.,Ltd";
    // MOVE.B,
    if (vendor_id == 0x18E6) return "MPL AG";
    if (vendor_id == 0x1B08) return "MSC Vertriebs GmbH";
    if (vendor_id == 0x1B7B) return "Multisuns Corporation";
    if (vendor_id == 0x1ED9) return "Myrtle.ai";
    if (vendor_id == 0x1CFC) return "Naltec, Inc.";
    if (vendor_id == 0x1F6B) return "Nanjing Houmo Technology Co.,Ltd.";
    if (vendor_id == 0x4C54) return "Nanjing Lisuan Technology Co., Ltd.";
    if (vendor_id == 0x1B8F) return "Nanoteq (Pty) Ltd";
    if (vendor_id == 0x18F4) return "Napatech AS";
    if (vendor_id == 0x1093) return "National Instruments Corporation";
    if (vendor_id == 0x1B4E) return "Nations Technologies Inc.";
    if (vendor_id == 0x1EBB) return "nCipher Security Ltd";
    if (vendor_id == 0x1F0F) return "Nebula Matrix";
    if (vendor_id == 0x4EEB) return "Nebulon Inc";
    if (vendor_id == 0x1BCF) return "NEC";
    if (vendor_id == 0x1E9A) return "Neoconix";
    if (vendor_id == 0x1D85) return "Neosem Holdings Inc";
    if (vendor_id == 0x1F40) return "Netac Technology Co.,Ltd";
    if (vendor_id == 0x1275) return "NetApp, Inc.";
    if (vendor_id == 0x1D82) return "NETINT Technologies Inc.";
    if (vendor_id == 0x1C1B) return "Netlist, Inc.";
    if (vendor_id == 0x19EE) return "Netronome";
    if (vendor_id == 0x1FD9) return "Neuchips Inc.";
    if (vendor_id == 0x1F49) return "NeuReality LTD";
    if (vendor_id == 0x1E73) return "NeuroBlade";
    if (vendor_id == 0x193D) return "New H3C Technologies Co., Ltd.";
    if (vendor_id == 0xAD10) return "New Wave Design and Verification, LLC";
    if (vendor_id == 0x1EA4) return "Newtech Co., Ltd.";
    if (vendor_id == 0x1933) return "Nexcom International";
    if (vendor_id == 0x1B07) return "NEXTCHIP Co,Ltd";
    if (vendor_id == 0x1F31) return "Nextorage Corporation";
    if (vendor_id == 0xCDFA) return "NextSilicon Ltd";
    if (vendor_id == 0x1F86) return "NEXTY Electronics Corporation";
    if (vendor_id == 0x1BB2) return "Nikon Corporation";
    if (vendor_id == 0x12E1) return "Nintendo Co., Ltd.";
    if (vendor_id == 0x1F4D) return "NIO Auto Co. Ltd.";
    if (vendor_id == 0x1F3D) return "nLIGHT Inc.";
    if (vendor_id == 0x13B8) return "Nokia Solutions and Networks Oy";
    if (vendor_id == 0x1B0C) return "Northrop Grumman Corp., Electronic Systems";
    if (vendor_id == 0x0222) return "Not for Radio, LLC";
    if (vendor_id == 0x1CBD) return "Novachips Co., Ltd";
    if (vendor_id == 0x1E09) return "Novatek Microelectronics Corporation";
    if (vendor_id == 0x1E02) return "NSITEXE, Inc.";
    if (vendor_id == 0x1646) return "NSW Inc.";
    if (vendor_id == 0x1EAA) return "NTP Technology AS";
    if (vendor_id == 0x12A4) return "NTT Electronics Corporation";
    if (vendor_id == 0x4E58) return "Nutanix, Inc.";
    if (vendor_id == 0x1808) return "nVent, Schroff GmbH";
    if (vendor_id == 0x10DE) return "NVidia Corporation";
    if (vendor_id == 0x1131) return "NXP Semiconductors";
    if (vendor_id == 0x16C8) return "Octasic Inc.";
    if (vendor_id == 0x1795) return "OKB SAPR";
    if (vendor_id == 0x1021) return "Oki Electric Industry Co., Ltd.";
    if (vendor_id == 0x1270) return "Olympus Corporation";
    if (vendor_id == 0x012E) return "OLZETEK";
    if (vendor_id == 0x10CB) return "Omron Corporation";
    if (vendor_id == 0x160C) return "OMS Motion, Inc.";
    if (vendor_id == 0x1529) return "ON Semiconductor";
    if (vendor_id == 0x1954) return "One Stop Systems, Inc.";
    if (vendor_id == 0x1E03) return "OnLogic, Inc.";
    if (vendor_id == 0x1BD9) return "Open Text Corporation";
    if (vendor_id == 0x1DF7) return "opencpi.org";
    if (vendor_id == 0x18FE) return "Opex Corporation";
    if (vendor_id == 0x148A) return "OPTO 22";
    if (vendor_id == 0x1F5E) return "Optos plc";
    if (vendor_id == 0x108E) return "Oracle";
    if (vendor_id == 0x1576) return "Osprey Video";
    if (vendor_id == 0x169A) return "Otari, Inc.";
    if (vendor_id == 0x1C7A) return "Other World Computing";
    if (vendor_id == 0x1E59) return "Oxford Nanopore Technologies plc";
    if (vendor_id == 0x01DE) return "Oxide Computer Company";
    if (vendor_id == 0x1EFA) return "Pacific Light & Hologram, Inc";
    if (vendor_id == 0x1569) return "Palit Microsystems Ltd.";
    if (vendor_id == 0x1EAF) return "Palo Alto Networks";
    if (vendor_id == 0x1189) return "Panasonic Corporation";
    if (vendor_id == 0x1AF8) return "Parade Technologies, Inc.";
    if (vendor_id == 0x1AB8) return "Parallels International GmbH";
    if (vendor_id == 0x1DDB) return "Parraid, LLC";
    if (vendor_id == 0x174B) return "PC Partner Limited";
    if (vendor_id == 0x001C) return "PEAK-System Technik GmbH";
    if (vendor_id == 0x1B0A) return "Pegatron Corporation";
    if (vendor_id == 0x1EFE) return "Peng Yu Trigold Limited";
    if (vendor_id == 0x1DD8) return "Pensando Systems";
    if (vendor_id == 0x12D8) return "Pericom Semiconductor";
    if (vendor_id == 0x1FCB) return "PerkinElmer";
    if (vendor_id == 0x1EE4) return "PetaIO Inc.";
    if (vendor_id == 0x9753) return "PEZY Computing K.K.";
    if (vendor_id == 0x1987) return "Phison Electronics Corporation";
    if (vendor_id == 0x1442) return "Phoenix Contact Electronics GmbH";
    if (vendor_id == 0x1363) return "Phoenix Technologies";
    if (vendor_id == 0x115C) return "Photron Limited";
    if (vendor_id == 0x1761) return "Pickering Interfaces Ltd.";
    if (vendor_id == 0x1EC4) return "Picocom Technology Limited";
    if (vendor_id == 0x1718) return "Pixela Corporation";
    if (vendor_id == 0x1EE2) return "plc2 Design GmbH";
    if (vendor_id == 0x1E7E) return "PLIOPS LTD.";
    if (vendor_id == 0x1D7F) return "Plugable";
    if (vendor_id == 0x15BB) return "Portwell, Inc.";
    if (vendor_id == 0x1F3A) return "Powerleader Computer System Co., Ltd.";
    if (vendor_id == 0x0CCD) return "Preferred Networks, Inc.";
    if (vendor_id == 0x1C67) return "PreSonus Audio Electronics Inc.";
    if (vendor_id == 0x160C) return "Pro-Dex, Oregon Micro Systems";
    if (vendor_id == 0x1C72) return "ProDesign Electronic GmbH";
    if (vendor_id == 0x1D13) return "Prodigy Technovations Private Limited";
    if (vendor_id == 0x1D33) return "Prodrive Technologies";
    if (vendor_id == 0x105A) return "Promise Technology, Inc.";
    if (vendor_id == 0x19D5) return "Protech Systems";
    if (vendor_id == 0x17C3) return "Protogate, Inc.";
    if (vendor_id == 0x1F92) return "PROXMEM (HK) TECHNOLOGY CO.,LIMITED";
    if (vendor_id == 0x1D00) return "Pure Storage, Inc.";
    if (vendor_id == 0x1F33) return "Purplelec Inc.Co.,Ltd";
    if (vendor_id == 0x1F7D) return "QBit Semiconductor LTD.";
    if (vendor_id == 0x1E34) return "Qrypt, Inc.";
    if (vendor_id == 0x1A9D) return "QSC Audio Products, LLC";
    if (vendor_id == 0x17CB) return "Qualcomm Incorporated";
    if (vendor_id == 0x1F70) return "Qualitas Semiconductor Co., Ltd.";
    if (vendor_id == 0x152D) return "Quanta Computer Inc.";
    if (vendor_id == 0x1D64) return "Quarch Technology Ltd";
    if (vendor_id == 0x1EAC) return "Quectel Wireless Solutions Co., Ltd.";
    if (vendor_id == 0x19D4) return "Quixant Plc";
    if (vendor_id == 0x1F90) return "QUSIDE TECHNOLOGIES S.L.";
    if (vendor_id == 0x1E81) return "Ramaxel Technology (Shenzhen) Limited";
    if (vendor_id == 0x19AA) return "Rambus Inc.";
    if (vendor_id == 0x1F91) return "Rapid Silicon US Inc";
    if (vendor_id == 0x1195) return "Ratoc Systems Inc.";
    if (vendor_id == 0x1E92) return "Raymax Technology Ltd.";
    if (vendor_id == 0x10B2) return "Raytheon Company";
    if (vendor_id == 0x17F3) return "RDC Semiconductor Co., Ltd.";
    if (vendor_id == 0x10EC) return "Realtek Semiconductor Corporation";
    if (vendor_id == 0x1EFF) return "Rebellions Inc.";
    if (vendor_id == 0x1BAD) return "REFLEX CES";
    if (vendor_id == 0x1960) return "REJ Co., Ltd.";
    if (vendor_id == 0x1912) return "Renesas Electronics Corporation";
    if (vendor_id == 0x163F) return "Renishaw plc.";
    if (vendor_id == 0x1180) return "Ricoh Company, Ltd.";
    if (vendor_id == 0x22A2) return "RIGOL TECHNOLOGIES CO., LTD.";
    if (vendor_id == 0x1B2E) return "Riverbed Technology, Inc.";
    if (vendor_id == 0x1EFD) return "Rivos Inc";
    if (vendor_id == 0x1D18) return "RME GmbH";
    //if (vendor_id == 0x3264) return "RnD Center \"ELVEES\", JSC (*Suspended)";
    if (vendor_id == 0x1D87) return "Rockchip Electronics Co., Ltd.";
    if (vendor_id == 0xF117) return "Rockport Networks Inc.";
    if (vendor_id == 0x12A0) return "Rockwell Automation Inc. (Allen-Bradley)";
    if (vendor_id == 0x162F) return "ROHDE & SCHWARZ GmbH & Co. KG";
    if (vendor_id == 0x10DB) return "Rohm Co., Ltd.";
    if (vendor_id == 0x16CE) return "Roland Corporation";
    if (vendor_id == 0x1F5B) return "Roscoe Software LLC";
    if (vendor_id == 0x1F62) return "Rosenberger Hochfrequenztechnik GmbH & Co.KG";
    if (vendor_id == 0x1CBF) return "Ross Video";
    if (vendor_id == 0x1435) return "RTD Embedded Technologies, Inc.";
    if (vendor_id == 0x1B86) return "Saab AB";
    if (vendor_id == 0x1EBC) return "Sabrent";
    //if (vendor_id == 0x1DD3) return "Sage Microelectronics Corp.(*Suspended)";
    if (vendor_id == 0x4547) return "Salland Engineering (Europe) b.v";
    if (vendor_id == 0x1E0D) return "SambaNova Systems, Inc.";
    if (vendor_id == 0x144D) return "Samsung Electronics Co., Ltd.";
    if (vendor_id == 0x1A82) return "Samtec";
    if (vendor_id == 0x1CC3) return "Sanmina";
    if (vendor_id == 0x1380) return "Sanritz Automation Co., Ltd.";
    if (vendor_id == 0x8686) return "SAP SE";
    if (vendor_id == 0x1F56) return "SAPEON Inc.";
    if (vendor_id == 0x1DA2) return "Sapphire Technology Limited";
    if (vendor_id == 0x174F) return "SAXA, Inc.";
    if (vendor_id == 0xCC53) return "ScaleFlux Inc.";
    if (vendor_id == 0x1F9A) return "Scalys BV";
    if (vendor_id == 0x1C2E) return "Schneider Electric Japan Holdings Ltd.";
    if (vendor_id == 0x1AA9) return "Schweitzer Engineering Labs, Inc.";
    if (vendor_id == 0x11C6) return "SCREEN GRAPHIC SOLUTIONS CO., LTD.";
    if (vendor_id == 0x1BB1) return "Seagate Technology LLC";
    if (vendor_id == 0x1A0D) return "SEAKR Engineering Inc.";
    if (vendor_id == 0x135E) return "Sealevel Systems, Inc.";
    if (vendor_id == 0x1BEC) return "SECO S.P.A.";
    if (vendor_id == 0x1CDD) return "Secunet Security Networks AG";
    if (vendor_id == 0x11DB) return "SEGA CORPORATION";
    if (vendor_id == 0x14EB) return "Seiko Epson Corporation";
    if (vendor_id == 0x1F26) return "SEMIFIVE, INC.";
    if (vendor_id == 0x1EB9) return "Senscomm Semiconductor Co., Ltd.";
    if (vendor_id == 0x1AB1) return "Sequans Communications";
    if (vendor_id == 0x1CB4) return "SerialTek";
    if (vendor_id == 0x1ED4) return "Shandong Exponent Semiconductor Co.,Ltd";
    if (vendor_id == 0x1EE0) return "Shanghai Biren Technology Co., Ltd";
    if (vendor_id == 0x41F8) return "Shanghai Cygnus Semiconductor Co.,Ltd.";
    if (vendor_id == 0x1F4F) return "Shanghai DaoCloud Network Technology Co,. Ltd";
    if (vendor_id == 0x1E27) return "Shanghai Denglin Technologies Co., Ltd";
    if (vendor_id == 0x1E36) return "Shanghai Enflame Technology Co. Ltd";
    if (vendor_id == 0x1E3E) return "Shanghai Iluvatar CoreX Semiconductor Co., Ltd.";
    if (vendor_id == 0x1F5D) return "Shanghai UniVista Industrial Software Group Co., Ltd.";
    if (vendor_id == 0x1F67) return "Shanghai Yunsilicon Technology Co,. Ltd.";
    if (vendor_id == 0x1D17) return "Shanghai Zhaoxin Semiconductor Co., Ltd.";
    if (vendor_id == 0x1CB0) return "Shannon Systems";
    if (vendor_id == 0x1D08) return "Shen Zhen Deren Electronic Co., LTD.";
    if (vendor_id == 0x8009) return "Shengli Technologies Co., Ltd";
    if (vendor_id == 0x1F3F) return "Shenzhen 3SNIC information technology company Limited";
    //if (vendor_id == 0x1642) return "Shenzhen Bitland Information Technology Co., Ltd (*Suspended)";
    if (vendor_id == 0x1F46) return "Shenzhen Chrent Technology Corp.";
    if (vendor_id == 0x7377) return "Shenzhen Colorful Yugong Technology and Development Co., Ltd.";
    if (vendor_id == 0x1F4A) return "Shenzhen Corerain Technologies. Co. Ltd.";
    if (vendor_id == 0x1E0B) return "Shenzhen Decenta Technology Co.,LTD";
    if (vendor_id == 0x1EB0) return "SHENZHEN ELECTRICAL APPLIANCES CO";
    if (vendor_id == 0x1EB3) return "Shenzhen Goodtimes Technology Co.,Ltd";
    if (vendor_id == 0x1F89) return "Shenzhen Gooxi Information Security Co.,Ltd.";
    if (vendor_id == 0x1EF7) return "Shenzhen Gunnir Technology Development Co., Ltd";
    if (vendor_id == 0x1F69) return "Shenzhen Haocheng Electronic Technology Co., Ltd";
    if (vendor_id == 0x1F66) return "Shenzhen Huahong Intelligence Co,.Ltd.";
    if (vendor_id == 0x1E63) return "Shenzhen iNet Mobile Internet Technology Co.,Ltd";
    if (vendor_id == 0x1F53) return "Shenzhen Jaguar Microsystems Co.,Ltd.";
    if (vendor_id == 0x1DF5) return "ShenZhen KIMTIGO Semiconductor Co., Ltd.";
    if (vendor_id == 0x1F4E) return "Shenzhen Konkr Technology Co., Ltd";
    if (vendor_id == 0x1D97) return "Shenzhen Longsys Electronics Co., Ltd.";
    if (vendor_id == 0x1F55) return "Shenzhen MADIGI Electronic Technology Co.,Ltd";
    if (vendor_id == 0x1F4C) return "Shenzhen Meigao Electronic Equipment Co.,Ltd";
    if (vendor_id == 0x1F75) return "Shenzhen One-Netbook Project Technology Co., Ltd";
    if (vendor_id == 0x1F73) return "Shenzhen Quanxing Tech Co., Ltd";
    if (vendor_id == 0x1F03) return "Shenzhen Shichuangyi Electronics Co., Ltd";
    if (vendor_id == 0x1E87) return "Shenzhen Shinning Electronic Co.,Ltd.";
    if (vendor_id == 0x1F99) return "Shenzhen Techwinsemi Technology Company Limited";
    if (vendor_id == 0x1F80) return "Shenzhen Tong Tai Yi information Technology Co.,Ltd";
    if (vendor_id == 0x1CC4) return "Shenzhen Unionmemory Information System Limited";
    if (vendor_id == 0x1ED3) return "SHENZHEN YINGJIAXUN INDUSTRY CO., LTD";
    if (vendor_id == 0x1C37) return "Shikino High-Tech Co., Ltd";
    if (vendor_id == 0x1C71) return "Shimadzu Corporation";
    if (vendor_id == 0x1F3B) return "Shunyao CAD (Shanghai) CO.,Ltd";
    if (vendor_id == 0x1297) return "Shuttle Inc";
    if (vendor_id == 0x1EA1) return "Sichuan Huafeng Technology Co., Ltd.";
    if (vendor_id == 0x110A) return "Siemens AG";
    if (vendor_id == 0x1F76) return "SiEngine Technology Co Ltd";
    if (vendor_id == 0x18D7) return "Sierra Wireless, Inc.";
    if (vendor_id == 0xF15E) return "SiFive, Inc.";
    if (vendor_id == 0x17D2) return "SigBitz LLC";
    if (vendor_id == 0x1F45) return "Signal Easy Technologies Co., Ltd.";
    if (vendor_id == 0x1BEB) return "SignalCore, Inc.";
    if (vendor_id == 0x1F8F) return "Signature Ip Corporation";
    if (vendor_id == 0x131F) return "SIIG Inc.";
    if (vendor_id == 0x1BCE) return "Silex Technology, Inc.";
    if (vendor_id == 0x1374) return "Silicom, Ltd.";
    if (vendor_id == 0x1E14) return "Silicon Creations, LLC";
    if (vendor_id == 0x1F39) return "Silicon Innovation Technologies Co., Ltd.";
    if (vendor_id == 0xA23B) return "Silicon Integrated Systems";
    if (vendor_id == 0x126F) return "Silicon Motion Inc.";
    if (vendor_id == 0x1F06) return "SiMa.ai";
    if (vendor_id == 0x1DF9) return "Simula Technology Inc.";
    if (vendor_id == 0x01B8) return "Sintela Ltd";
    if (vendor_id == 0x1F87) return "SiTime Corp.";
    if (vendor_id == 0x025E) return "SK hynix Inc.";
    if (vendor_id == 0x1543) return "Skyworks Solutions, Inc.";
    if (vendor_id == 0x1EF2) return "Smart IOPS, Inc.";
    if (vendor_id == 0x1235) return "SMART Modular Technologies";
    if (vendor_id == 0x1CDF) return "SmartDV North America, LLC";
    if (vendor_id == 0x50C1) return "Socionext Inc.";
    if (vendor_id == 0x14A0) return "Softing AG";
    if (vendor_id == 0x1D1E) return "Solid State System";
    if (vendor_id == 0xD063) return "SolidRun Ltd";
    if (vendor_id == 0x1BC9) return "Sonifex Ltd";
    if (vendor_id == 0x104D) return "Sony Group Corporation";
    if (vendor_id == 0x1F1C) return "SOPHGO Technologies Ltd.";
    if (vendor_id == 0x1E31) return "SORD Corporation";
    if (vendor_id == 0x1B37) return "SP Devices";
    if (vendor_id == 0x1DAC) return "SparkLAN Communications, Inc.";
    if (vendor_id == 0x172F) return "Sparkle Computer Co., Ltd.";
    if (vendor_id == 0x18F1) return "Spectrum Instrumentation GmbH";
    if (vendor_id == 0xDA7A) return "Speedata Inc.";
    if (vendor_id == 0x174A) return "Spirent Communications";
    if (vendor_id == 0x1DC7) return "SSI Computer Corp";
    if (vendor_id == 0x1A8A) return "Star Bridge, Inc.";
    if (vendor_id == 0x1BCA) return "Star Communications, Inc.";
    if (vendor_id == 0x1974) return "STAR Electronics GmbH & Co. KG";
    if (vendor_id == 0x1B5E) return "Star-Dundee Ltd.";
    if (vendor_id == 0x1B45) return "StarTech.com Ltd.";
    if (vendor_id == 0x1683) return "StepTechnica Co., Ltd.";
    if (vendor_id == 0x104A) return "STMicroelectronics International NV";
    if (vendor_id == 0x8080) return "StoreSwift Technology Co., Ltd.";
    if (vendor_id == 0x159C) return "Stratus Technologies, Inc.";
    if (vendor_id == 0x23E2) return "streamcomputing";
    if (vendor_id == 0x1CF7) return "Subspace Dynamics LLC";
    if (vendor_id == 0x1349) return "Sumitomo Electric Industries, Ltd.";
    if (vendor_id == 0x1FD4) return "Sunix Co., Ltd.";
    if (vendor_id == 0x3DEE) return "SunRise Memory Corp.";
    if (vendor_id == 0x15D9) return "Super Micro Computer Inc.";
    if (vendor_id == 0x1EE9) return "SUSE LLC";
    if (vendor_id == 0x1F78) return "Suvaca Technologies Private Limited";
    if (vendor_id == 0x1EE1) return "Suzhou Kuhan Information technologies";
    if (vendor_id == 0xFFE1) return "Suzhou XiongLi Technology Inc.";
    if (vendor_id == 0x1DD4) return "Swissbit AG";
    if (vendor_id == 0x1E01) return "Synaptics, Inc.";
    if (vendor_id == 0x1CA1) return "Sync-n-Scale, LLC";
    if (vendor_id == 0x7053) return "Synology Inc.";
    if (vendor_id == 0x16C3) return "Synopsys, Inc.";
    if (vendor_id == 0x184B) return "SYSTEC Corporation";
    //if (vendor_id == 0x1E47) return "SZ DJI Technology Co., Ltd. (*Suspended)";
    if (vendor_id == 0x1A12) return "Taiwan Commate Computer";
    if (vendor_id == 0x1CEB) return "Taiwan Pulse Motion Co., Ltd.";
    if (vendor_id == 0x1ED7) return "TARGETEK Ltd.";
    if (vendor_id == 0x12AF) return "TDK Corporation";
    if (vendor_id == 0x1513) return "TE Connectivity";
    if (vendor_id == 0x1227) return "Tech Source Inc.";
    if (vendor_id == 0x1D61) return "Technobox, Inc.";
    if (vendor_id == 0x1F6E) return "Technolution B.V.";
    if (vendor_id == 0x1C4E) return "Techway";
    if (vendor_id == 0x1F5C) return "TECNO MOBILE LIMITED";
    if (vendor_id == 0x1DA1) return "Teko Telecom S.r.l. a Socio Unico";
    if (vendor_id == 0x1268) return "Tektronix";
    if (vendor_id == 0x1D88) return "Telechips Inc.";
    if (vendor_id == 0x11EC) return "Teledyne Dalsa";
    if (vendor_id == 0x1B6B) return "Teledyne Digital Imaging dba Teledyne Photometrics dba Teledyne QImaging";
    if (vendor_id == 0x1F54) return "Teledyne FLIR";
    if (vendor_id == 0x1570) return "Teledyne LeCroy";
    if (vendor_id == 0x1B37) return "Teledyne SP Devices";
    if (vendor_id == 0x13E5) return "Telesoft Technologies Ltd.";
    if (vendor_id == 0x1F57) return "Teletrx Co.";
    if (vendor_id == 0xFE19) return "TenaFe Inc.";
    if (vendor_id == 0x1EA0) return "Tencent Technology (Shenzhen) Company Limited";
    if (vendor_id == 0x1E52) return "Tenstorrent Inc";
    if (vendor_id == 0x1316) return "Teradyne, Inc.";
    if (vendor_id == 0x751A) return "Tesla Inc";
    if (vendor_id == 0x1F63) return "Tessolve Semiconductor Pvt Ltd";
    if (vendor_id == 0x1498) return "TEWS Technologies GmbH";
    if (vendor_id == 0x104C) return "Texas Instruments";
    if (vendor_id == 0x1269) return "Thales";
    if (vendor_id == 0x1BD5) return "The FreeBSD Foundation";
    if (vendor_id == 0x1BE9) return "The MathWorks, Inc.";
    if (vendor_id == 0x1168) return "Thine Electronics, Inc";
    if (vendor_id == 0x14D2) return "TITAN Electronics Inc.";
    if (vendor_id == 0x1BC8) return "TokushuDenshiKairo Inc.";
    if (vendor_id == 0x1679) return "Tokyo Electron Device Ltd.";
    if (vendor_id == 0x138B) return "TOKYO KEIKI INC.";
    if (vendor_id == 0x1D05) return "TONGFANG HONGKONG LIMITED";
    if (vendor_id == 0x1D45) return "Top Victory Investments Limited";
    if (vendor_id == 0x1179) return "Toshiba Corporation";
    if (vendor_id == 0x15A5) return "Toyota Technical Development Corporation";
    if (vendor_id == 0x1EEE) return "Tracewell Systems, Inc.";
    if (vendor_id == 0x1D79) return "Transcend Information, Inc.";
    if (vendor_id == 0x1A3D) return "Tritek Co., Ltd.";
    if (vendor_id == 0x1C64) return "TRS-RenTelco";
    if (vendor_id == 0x1DD1) return "Truechip Solutions Pvt. Ltd.";
    if (vendor_id == 0x1C7E) return "TTTech Computertechnik AG";
    if (vendor_id == 0x148C) return "Tul Corporation";
    if (vendor_id == 0x1F61) return "TuSimple";
    if (vendor_id == 0x1E32) return "Tuxera Inc.";
    if (vendor_id == 0x14FF) return "Twinhead International Corporation";
    if (vendor_id == 0x1962) return "U.S. Patent & Trademark Office";
    if (vendor_id == 0x19BC) return "Ueda Japan Radio Co., Ltd.";
    // UL Solutions,
    if (vendor_id == 0x18D1) return "ULVAC-PHI, Inc.";
    if (vendor_id == 0x1C1A) return "UNH InterOperability Laboratory";
    if (vendor_id == 0x1C1A) return "UNH InterOperability Laboratory (UNH-IOL)";
    if (vendor_id == 0x19BF) return "Unicom Engineering Inc";
    if (vendor_id == 0x0526) return "Unicompute Technology Co., Ltd.";
    if (vendor_id == 0x1D83) return "Uniconn Corp.";
    if (vendor_id == 0x1FAB) return "UniFabriX Ltd.";
    if (vendor_id == 0x1CC2) return "Unigen Corporation";
    if (vendor_id == 0x1DB3) return "Unisoc (Shanghai) Technologies Co., Ltd.";
    if (vendor_id == 0x1018) return "Unisys Corporation";
    if (vendor_id == 0x1DC9) return "UniTest";
    if (vendor_id == 0x1A00) return "Universal Audio, Inc.";
    if (vendor_id == 0x14CD) return "Universal Global Scientific Industrial Co., Ltd";
    if (vendor_id == 0x1E67) return "Untether AI Corporation";
    if (vendor_id == 0x1DA5) return "UTran Technology Inc.";
    if (vendor_id == 0x1DF8) return "V&G Information System Co.,Ltd";
    if (vendor_id == 0xABCD) return "Vadatech Inc.";
    if (vendor_id == 0x1D19) return "VAIO Corporation";
    if (vendor_id == 0x1DDE) return "Valens Semiconductor Ltd.";
    if (vendor_id == 0x1E44) return "Valve Software";
    if (vendor_id == 0x1FCB) return "Varex Imaging Deutschland AG";
    if (vendor_id == 0x1E46) return "Varjo Technologies Oy";
    if (vendor_id == 0x1F77) return "Vast Data LTD";
    if (vendor_id == 0x1EC6) return "Vastai Technologies (Shanghai) Inc";
    if (vendor_id == 0x1DAE) return "Vectology,Inc.";
    if (vendor_id == 0x19E2) return "Vector Informatik GmbH";
    if (vendor_id == 0x1F97) return "Ventana Micro Systems Inc";
    if (vendor_id == 0x144B) return "Verint";
    if (vendor_id == 0x1E9D) return "VersaLogic Corporation";
    if (vendor_id == 0x1106) return "VIA Technologies, Inc.";
    if (vendor_id == 0x1B83) return "Viasat Inc.";
    if (vendor_id == 0x1D7D) return "Viavi Solutions";
    if (vendor_id == 0x156C) return "VMagic Electronics GmbH";
    if (vendor_id == 0x15AD) return "Vmware, Inc.";
    // VTM Group,
    if (vendor_id == 0x1F44) return "VVDN Technologies. Private Limited";
    if (vendor_id == 0x5658) return "VX Instruments GmbH";
    if (vendor_id == 0x5743) return "WALTON DIGI-TECH INDUSTRIES LIMITED";
    if (vendor_id == 0x1B96) return "Western Digital Technologies, Inc.";
    if (vendor_id == 0x1C6C) return "Wibtek Electronics Co., Ltd";
    if (vendor_id == 0x1E15) return "Wieson Technologies Co., LTD.";
    if (vendor_id == 0x1F58) return "Wild River Technologies LLC";
    if (vendor_id == 0x1CCE) return "Wilder Technologies";
    if (vendor_id == 0x1F7E) return "WILK ELEKTRONIK S.A.";
    if (vendor_id == 0x1E75) return "Wind River Systems, Inc.";
    if (vendor_id == 0x1EC9) return "Wingtech Group(HongKong)Limited";
    if (vendor_id == 0x1EA8) return "Winintec";
    if (vendor_id == 0x1EF5) return "Winmate Inc.";
    if (vendor_id == 0x1B17) return "WinSystems, Inc.";
    if (vendor_id == 0x1E86) return "Wintec Industries, Inc.";
    if (vendor_id == 0x1811) return "Wipro Technologies";
    if (vendor_id == 0x1F38) return "Wisewave Technology Co., Ltd";
    if (vendor_id == 0x17C0) return "Wistron Corporation";
    if (vendor_id == 0x1F48) return "Wistron NeWeb Corp.";
    if (vendor_id == 0x1EC1) return "Wiwynn Corporation";
    if (vendor_id == 0x1F05) return "WLCO(ShenZhen) Co.,Ltd.";
    if (vendor_id == 0x301F) return "WOLF Advanced Technology";
    if (vendor_id == 0x1F15) return "Wolley (Taiwan) Ltd.";
    if (vendor_id == 0x1F65) return "Wuhan Lixi Intelligent Manufacturing Co., Ltd.";
    if (vendor_id == 0x1F32) return "Wuhan YuXin Semiconductor Co., Ltd.";
    if (vendor_id == 0x1F19) return "Wuxi High Information Security Technology Co. ,Ltd.";
    if (vendor_id == 0x8848) return "Wuxi Micro Innovation Integrated Circuit Design Co.,Ltd";
    if (vendor_id == 0x1EB6) return "Wuxi Stars Microsystem Technology Co., Ltd";
    if (vendor_id == 0x1F16) return "Xconn Technologies Holdings, Inc.";
    if (vendor_id == 0x1F7F) return "XEPIC Corporation Limited";
    if (vendor_id == 0x10C5) return "Xerox Corporation";
    if (vendor_id == 0x1F24) return "xFusion Digital Technologies Co., Limited";
    if (vendor_id == 0x1EAE) return "XFX Limited";
    if (vendor_id == 0x8510) return "Xi'an Sietium Semicoductor CO., LTD";
    if (vendor_id == 0x1EED) return "Xiangdixian Computing Technology (Chongqing) Limited Company";
    if (vendor_id == 0x1D72) return "Xiaomi Communications Co., Ltd.";
    if (vendor_id == 0x10EE) return "Xilinx, Inc.";
    if (vendor_id == 0xDEDA) return "XIMEA";
    if (vendor_id == 0x1C5B) return "XJTAG Ltd.";
    if (vendor_id == 0x1E6C) return "Xsight Labs Ltd";
    if (vendor_id == 0x1D93) return "YADRO";
    if (vendor_id == 0x1073) return "Yamaha Corporation";
    if (vendor_id == 0x18B4) return "Yamaichi Electronics";
    if (vendor_id == 0x150B) return "Yamashita Systems Corp";
    if (vendor_id == 0x1E49) return "Yangtze Memory Technologies Co.,Ltd";
    if (vendor_id == 0x1313) return "YASKAWA Electric Corporation";
    if (vendor_id == 0x1D89) return "YEESTOR Microelectronics Co., Ltd";
    if (vendor_id == 0x1281) return "Yokogawa Electric Corporation";
    if (vendor_id == 0x1F47) return "YUSUR Technology Co., Ltd.";
    if (vendor_id == 0x1D6B) return "ZAO Kraftway Corporation PLC";
    if (vendor_id == 0x1EF9) return "Zeku Technology (Shanghai) Corp., Ltd.";
    if (vendor_id == 0x1F17) return "Zettastone Technology (wuhan) Co.,Ltd";
    if (vendor_id == 0x1E76) return "Zhejiang Zhaolong Interconnect Technology Co., Ltd";
    if (vendor_id == 0x1E72) return "Zoox Inc";
    if (vendor_id == 0x6899) return "ZT Systems";
    if (vendor_id == 0x1CF2) return "ZTE Corporation";
    return "Unknown Vendor ID";
}